### ISSUE TITLE
Widget de Relógio 

### ISSUE THREAD

**Issue by EduardoRGCM** [EduardoRGCM/HyperOS-XML-1.0-BRAZILIAN#84]
Neste Widget de relógio, o dia da semana e a data deveriam estar abreviadas em pt_BR para se adequar à versão padrão.

![IMG_20241122_170727.jpg](https://github.com/user-attachments/assets/f1c764a0-1c2d-4142-a9c6-ecba242197bd)

**Comment by igormiguell** [comment]
Dei uma modificada, se não corrigir me fale.

**Comment by EduardoRGCM** [comment]
![Screenshot_2024-11-26-13-01-35-690_com.miui.home.jpg](https://github.com/user-attachments/assets/ab31dbb6-ea22-4314-b8f2-0310c5ec021c)
Mesmo após atualização, o widget continua com a data por extenso.

**Comment by EduardoRGCM** [comment]
@igormiguell vou fechar o issue porque não é possível corrigir alterando a tradução no repo, é necessário fazer as correções diretamente no widget, em breve será corrigido.
